name: CI PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: linux jdk8
            java: 8
            disable-samples: true
          - nickname: linux jdk11
            java: 11
            disable-samples: false
          - nickname: linux jdk17
            java: 17
            disable-samples: false
    name: CI PR ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build
        env:
          DISABLE_SAMPLES: ${{ matrix.disable-samples }}
        run: ./mvnw -B package
